services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8226:8080"
    volumes:
      - ./logs:/app/logs
    environment:
        - SPRING_PROFILES_ACTIVE=prod



